import type { Metadata } from "next";
import "./globals.css";
import { Grain } from "@/components/Grain";
import Headline from "@/components/Headline";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SmoothScrolling from "@/components/ui/SmoothScrolling";
import { Providers } from "./providers";
import BackgroundWrapper from "@/components/ui/BackgroundComponnet";

export const metadata: Metadata = {
  title: "Axbhxs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const title = "Aabhas";

  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Providers>
          <BackgroundWrapper>
            <SmoothScrolling>
              <Grain />
              <Headline title={title} />
              <Navbar />
              {children}
              <Footer />
              <div className="lg:hidden">
                <Headline title={title} />
              </div>
            </SmoothScrolling>
          </BackgroundWrapper>
        </Providers>
      </body>
    </html>
  );
}
