import type { Metadata } from "next";
import "./globals.css";
import { Grain } from "@/components/Grain";
import Headline from "@/components/Headline";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SmoothScrolling from "@/components/ui/SmoothScrolling";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const title = "Aabhas";

  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Providers>
          <SmoothScrolling>
            <Grain />
            <Headline title={title} />
            <Navbar />
            {children}
            <Footer />
            {/* <Headline title={title} /> */}
          </SmoothScrolling>
        </Providers>
      </body>
    </html>
  );
}
